### ISSUE TITLE
Use string substitution for logging

### ISSUE THREAD

**Issue by Ryuno-Ki** [ionicc/Github-organization-inviter#14]
This is a follow-up of #8.

In STDOUT you can sometimes see `[object Object]`.
e.g. for https://github.com/ionicc/Github-organization-inviter/blob/5381d04484b94a64d836c6b215ce67827fa58e72/main.js#L34
This could be evaded by using [string substitution](https://developer.mozilla.org/en-US/docs/Web/API/console#Using_string_substitutions) in the log call.

**Comment by ionicc** [comment]
@Ryuno-Ki Can you take this up?
