### ISSUE TITLE
Prefer environment variable over hardcoded value

### ISSUE THREAD

**Issue by Ryuno-Ki** [ionicc/Github-organization-inviter#17]
This is a follow-up of #8.

https://github.com/ionicc/Github-organization-inviter/blob/5381d04484b94a64d836c6b215ce67827fa58e72/main.js#L21 shows that there would be a way to modify the served port.
However, since `8000` is truthy, the right hand side (`process.env.PORT`) is never evaluated.
Switch the order and you are good to go.

**Comment by ionicc** [comment]
Ah yeah, I did this because of the Nginx reverse proxy I've used in my production version. It's easy to map the port in Nginx config if you have a hardcoded/constant port value.
If we shift it to process.env.PORT then how will we dynamically map the ports?

**Comment by Ryuno-Ki** [comment]
Not sure, whether I get you here. Dynamic port mapping?

```bash
node main.js  # port 8000
PORT=8080 node main.js  # port 8080
```

**Comment by hood** [comment]
This could be closed now.

**Comment by Ryuno-Ki** [comment]
Thanks forthe PR!
